#!/bin/bash

# Where we start.
#
# @private
function run() {
  if [[ ! "$MIGRATE" == "false" ]]; then
    migrate
  fi

  # Run the command
  eval "$1"
}

# Applies migration.
#
# @private
function migrate() {
  LIQUIBASE_HOME=/usr/local/bin/liquibase
  MIGRATION_HOME=/app/.migrations

  # Create database if not exists
  export PGPASSWORD="$DATABASE_PASSWORD"
  echo "SELECT 'CREATE DATABASE $DATABASE_NAME' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DATABASE_NAME')\gexec" | psql -h "$DATABASE_HOST" -U "$DATABASE_USERNAME"

  # Migrate
  cd "$MIGRATION_HOME" || fatal "Migration directory $MIGRATION_HOME not found"

  "$LIQUIBASE_HOME"/liquibase \
    --changelog-file="db.changelog-master.xml" \
    --url="jdbc:postgresql://$DATABASE_HOST/$DATABASE_NAME" \
    --username="$DATABASE_USERNAME" \
    --password="$DATABASE_PASSWORD" \
    --promptForNonLocalDatabase=false \
    --hub-mode=off \
    update
}

# @private
function fatal() {
  printf "ERROR: %s\\n" "$*" >&2
  exit 1
}

run "$@"
