#!/bin/bash

# Where we start.
#
# @private
function run() {
  if [[ ! "$MIGRATE" == "false" ]]; then
    migrate
  fi

  # Run the command
  eval "$1"
}

# Applies migration.
#
# @private
function migrate() {
  # Create database if not exists
  export PGPASSWORD="$DATABASE_PASSWORD"
  echo "SELECT 'CREATE DATABASE $DATABASE_NAME' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DATABASE_NAME')\gexec" | psql -h "$DATABASE_HOST" -U "$DATABASE_USERNAME"

  # Migrate
  /usr/local/bin/migrate/migrate \
    -source file:/app/.migrations \
    -database "postgres://$DATABASE_USERNAME:$DATABASE_PASSWORD@$DATABASE_HOST/$DATABASE_NAME" \
    up
}

run "$@"
