// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       string
	Name     string
	ParentID pgtype.Text
}
