// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        string
	Name      string
	Email     *string
	Phone     *string
	PixKey    *string
	DeletedAt pgtype.Timestamp
	UserID    string
}

type ContactHistory struct {
	ID          string
	Name        string
	Email       *string
	Phone       *string
	PixKey      *string
	EffectiveAt pgtype.Timestamp
	ContactID   string
}
