// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dao

import ()

type Bank struct {
	Id   string
	Name string
	Ispb string
}

type BankDetail struct {
	Id            string
	BranchNumber  int32
	AccountNumber int32
	AccountType   string
	PixKey        string
	IsPrimary     interface{}
	BankId        string
	ContactId     string
}

type Contact struct {
	Id     string
	Name   string
	Email  string
	Phone  string
	TaxId  string
	UserId string
}
