// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dao

import ()

type BankDetail struct {
	ID            string
	BranchNumber  int32
	AccountNumber int32
	AccountType   string
	PixKey        string
	Main          bool
	BankID        string
	ContactID     string
}

type Contact struct {
	ID     string
	Name   string
	Email  string
	Phone  string
	TaxID  string
	UserID string
}
