// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package dao

import (
	"context"
)

const getContacts = `-- name: GetContacts :one
SELECT id, name, email, phone, tax_id, user_id FROM contacts
`

func (q *Queries) GetContacts(ctx context.Context) (Contact, error) {
	row := q.db.QueryRow(ctx, getContacts)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.TaxID,
		&i.UserID,
	)
	return i, err
}
