// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dao

import (
	"context"
)

type Querier interface {
	GetContacts(ctx context.Context) (Contact, error)
}

var _ Querier = (*Queries)(nil)
