// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dao

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) error
	CreateContactHistory(ctx context.Context, arg CreateContactHistoryParams) error
	ExistsContactByID(ctx context.Context, arg ExistsContactByIDParams) (bool, error)
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error)
	GetContacts(ctx context.Context, userID string) ([]Contact, error)
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) error
	UpdateContact(ctx context.Context, arg UpdateContactParams) error
}

var _ Querier = (*Queries)(nil)
