// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dao

import ()

type Account struct {
	ID     string
	Name   string
	BankID string
	UserID string
}

type Bank struct {
	ID   string
	Name string
	Ispb string
}
