// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package dao

import (
	"context"
)

const getAccounts = `-- name: GetAccounts :one
SELECT id, name, bank_id, user_id FROM accounts
`

func (q *Queries) GetAccounts(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getAccounts)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BankID,
		&i.UserID,
	)
	return i, err
}
