// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dao

import ()

type Setting struct {
	Id    string
	Key   string
	Value string
}

type UserSetting struct {
	Id     string
	Key    string
	Value  string
	UserID string
}
