// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: queries.sql

package dao

import (
	"context"
)

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, key, value FROM settings WHERE key = $1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, key)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const getUserSettingByKey = `-- name: GetUserSettingByKey :one
SELECT id, key, value, user_id FROM user_settings WHERE key = $1 AND user_id = $2
`

type GetUserSettingByKeyParams struct {
	Key    string
	UserID string
}

func (q *Queries) GetUserSettingByKey(ctx context.Context, arg GetUserSettingByKeyParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettingByKey, arg.Key, arg.UserID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.UserID,
	)
	return i, err
}

const updateUserSetting = `-- name: UpdateUserSetting :exec
INSERT INTO user_settings (id, key, value, user_id)
VALUES ($1, $2, $3, $4) ON CONFLICT (key, user_id) DO
UPDATE SET value = $3
`

type UpdateUserSettingParams struct {
	ID     string
	Key    string
	Value  string
	UserID string
}

func (q *Queries) UpdateUserSetting(ctx context.Context, arg UpdateUserSettingParams) error {
	_, err := q.db.Exec(ctx, updateUserSetting,
		arg.ID,
		arg.Key,
		arg.Value,
		arg.UserID,
	)
	return err
}
