// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dao

import (
	"context"
)

type Querier interface {
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	GetUserSettingByKey(ctx context.Context, arg GetUserSettingByKeyParams) (UserSetting, error)
	UpdateUserSetting(ctx context.Context, arg UpdateUserSettingParams) error
}

var _ Querier = (*Queries)(nil)
