// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package dao

import (
	"context"
)

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, key, value FROM settings WHERE key = $1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, key)
	var i Setting
	err := row.Scan(&i.Id, &i.Key, &i.Value)
	return i, err
}

const updateSetting = `-- name: UpdateSetting :exec
INSERT INTO settings (id, key, value)
VALUES ($1, $2, $3) ON CONFLICT (key) DO
UPDATE SET value = $3
`

type UpdateSettingParams struct {
	Id    string
	Key   string
	Value string
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.Exec(ctx, updateSetting, arg.Id, arg.Key, arg.Value)
	return err
}
