// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dao

import (
	"context"
)

type Querier interface {
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) error
}

var _ Querier = (*Queries)(nil)
