// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dao

import (
	"context"
)

type Querier interface {
	DeleteSettingByKey(ctx context.Context, arg DeleteSettingByKeyParams) error
	ExistsSettingByKey(ctx context.Context, arg ExistsSettingByKeyParams) (bool, error)
	GetSettingByKey(ctx context.Context, arg GetSettingByKeyParams) (Setting, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) error
}

var _ Querier = (*Queries)(nil)
