// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bill struct {
	ID          string
	Description string
	Amount      pgtype.Numeric
	Status      string
	DueAt       pgtype.Timestamp
	PaidAt      pgtype.Timestamp
	CategoryID  string
	ContactID   string
	UserID      string
}

type RecurringBill struct {
	ID          string
	Description string
	Amount      pgtype.Numeric
	Frequency   string
	StartAt     pgtype.Date
	EndAt       pgtype.Date
	ContactID   string
	CategoryID  string
	UserID      string
}
