// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bill struct {
	ID          string
	Description string
	Type        string
	DueAt       pgtype.Date
	Amount      float64
	Status      string
	CategoryID  string
	ContactID   string
	UserID      string
}

type Boleto struct {
	ID      string
	Barcode string
	BillID  string
}

type Payment struct {
	ID     string
	Date   pgtype.Date
	Amount float64
	BillID string
}

type RecurringBill struct {
	ID          string
	Description string
	Type        string
	StartAt     pgtype.Date
	EndAt       pgtype.Date
	Amount      float64
	Interval    string
	ContactID   string
	CategoryID  string
	UserID      string
}
