// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetRecurringBillsByRange(ctx context.Context, date pgtype.Date) ([]RecurringBill, error)
}

var _ Querier = (*Queries)(nil)
