// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecurringBillsByRange = `-- name: GetRecurringBillsByRange :many
SELECT id, description, amount, frequency, start_at, end_at, contact_id, category_id, user_id FROM recurring_bills WHERE start_at::date = $1 AND start_at::date = $1 AND end_at::date <= $1
`

func (q *Queries) GetRecurringBillsByRange(ctx context.Context, date pgtype.Date) ([]RecurringBill, error) {
	rows, err := q.db.Query(ctx, getRecurringBillsByRange, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringBill{}
	for rows.Next() {
		var i RecurringBill
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Frequency,
			&i.StartAt,
			&i.EndAt,
			&i.ContactID,
			&i.CategoryID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
