// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dao

import (
	"context"
)

type Querier interface {
	CreateBill(ctx context.Context, arg CreateBillParams) error
	CreateBoleto(ctx context.Context, arg CreateBoletoParams) error
	CreateRecurringBill(ctx context.Context, arg CreateRecurringBillParams) error
}

var _ Querier = (*Queries)(nil)
