// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dao

import (
	"time"
)

type ExchangeRate struct {
	Id     string
	Date   time.Time
	Source string
	Target string
	Rate   float64
}
