// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExchangeCurrency struct {
	Id     string
	Source string
	Target string
}

type ExchangeRate struct {
	Id        string
	Date      pgtype.Date
	Source    string
	Target    string
	Rate      float64
	CreatedAt pgtype.Timestamp
}
