// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: queries.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExchangeRate = `-- name: CreateExchangeRate :exec
INSERT INTO exchange_rates (id, date, source, target, rate, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateExchangeRateParams struct {
	ID        string
	Date      pgtype.Date
	Source    string
	Target    string
	Rate      float64
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) error {
	_, err := q.db.Exec(ctx, createExchangeRate,
		arg.ID,
		arg.Date,
		arg.Source,
		arg.Target,
		arg.Rate,
		arg.CreatedAt,
	)
	return err
}

const getExchangeCurrencies = `-- name: GetExchangeCurrencies :many
SELECT id, source, target FROM exchange_currencies
`

func (q *Queries) GetExchangeCurrencies(ctx context.Context) ([]ExchangeCurrency, error) {
	rows, err := q.db.Query(ctx, getExchangeCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeCurrency{}
	for rows.Next() {
		var i ExchangeCurrency
		if err := rows.Scan(&i.ID, &i.Source, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExchangeRateForConversion = `-- name: GetExchangeRateForConversion :one
SELECT id, date, source, target, rate, created_at
  FROM exchange_rates
 WHERE created_at::date = $1::date
   AND source = $2
   AND target = $3
 ORDER BY created_at DESC
 LIMIT 1
`

type GetExchangeRateForConversionParams struct {
	CreatedAt pgtype.Date
	Source    string
	Target    string
}

func (q *Queries) GetExchangeRateForConversion(ctx context.Context, arg GetExchangeRateForConversionParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRateForConversion, arg.CreatedAt, arg.Source, arg.Target)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Source,
		&i.Target,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}
