// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dao

import (
	"context"
)

type Querier interface {
	GetExchangeRate(ctx context.Context) (ExchangeRate, error)
	GetExchangeRateForConversion(ctx context.Context, arg GetExchangeRateForConversionParams) (ExchangeRate, error)
	UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) error
}

var _ Querier = (*Queries)(nil)
