// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package dao

import (
	"context"
	"time"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT id, date, source, target, rate FROM exchange_rates WHERE date = now()::date
`

func (q *Queries) GetExchangeRate(ctx context.Context) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRate)
	var i ExchangeRate
	err := row.Scan(
		&i.Id,
		&i.Date,
		&i.Source,
		&i.Target,
		&i.Rate,
	)
	return i, err
}

const updateExchangeRate = `-- name: UpdateExchangeRate :exec
INSERT INTO exchange_rates (id, date, source, target, rate)
  VALUES ($1, $2, $3, $4, $5)
  ON CONFLICT (date, source, target) DO UPDATE SET rate = $5
`

type UpdateExchangeRateParams struct {
	Id     string
	Date   time.Time
	Source string
	Target string
	Rate   float64
}

func (q *Queries) UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) error {
	_, err := q.db.Exec(ctx, updateExchangeRate,
		arg.Id,
		arg.Date,
		arg.Source,
		arg.Target,
		arg.Rate,
	)
	return err
}
