name: Publish image
on:
  push:
    tags:
      - v*
jobs:
  publish-image:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}:${{ steps.get_tag.outputs.VERSION }}
          build-args: |
            ACCESS_USERNAME=${{ secrets.ACCESS_USERNAME }}
            ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
