name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Get Dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...